---
version: '3.8'

services:
  onesy-redis:
    image: redis:6.2-alpine
    restart: always
    volumes:
      - '~/.onesy/redis:/.redis'
    ports:
      - '6379:6379'

  onesy-redis-test:
    image: redis:6.2-alpine
    restart: always
    volumes:
      - '~/.onesy/test/redis:/.redis'
    ports:
      - '7379:6379'
